version: '3.8'

services:
  mcp-math-toolkit:
    build: .
    container_name: mcp-math-toolkit
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # For stdio-based MCP, we typically don't expose ports
    # but this can be useful for debugging
    ports:
      - "3000:3000"
    # Mount source for development (optional)
    # volumes:
    #   - ./src:/app/src:ro
    
  # Development service with live reload
  mcp-math-toolkit-dev:
    build: 
      context: .
      target: development
    container_name: mcp-math-toolkit-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
    ports:
      - "3001:3000"
    command: npm run dev
    profiles: ["dev"]
